apiVersion: v1
kind: Secret
metadata:
    name: dev-cluster-spec
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: dev-cluster
    config: ENC[AES256_GCM,data:KgwWnhpgE7kKe1HP2aguW7GliFxsSaS6uC/55h5cqS0k/3YdetB0mv5y5Iu2d9rTNW1nIB2Hk7GHp80ypzVAIYydXDpOEZb/SEzX1BCD/A==,iv:6m5rQPEzovX4TYJlGvAH0c0azgy/IKRrQ0HvGC8Ej3s=,tag:SIthVxHVhuB8tMGuXd1vHw==,type:str]
    namespaces: aicoe-argocd-dev,argocd-test
    server: API_SERVER
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-04T14:04:56Z'
    mac: ENC[AES256_GCM,data:zFcY9zKZr/osSeldf5f4QEUaSfMoV30SLdaTnw0A4QGkwIfxNpcAqDDZhRJzDNlKw8kNurwfd80g1MVYTn8/37vesNXF2eJ64aX+Dv8RlJIZvhuiK1gRUdW7uDE47giOwTN7H20NrfljbhzP9PK4iACBYFqPjVq5h7Slmt/sNXM=,iv:0/2KPHu0AXTbgcryGkUg4RdzVGT1UBAKWmYGxHY+Syk=,tag:JuDtkMKjwBKGZbdHXEn/Jg==,type:str]
    pgp:
    -   created_at: '2020-09-04T14:04:56Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA4ewWWewNLhTAQf/Ujky/5aWwkPYvU+6w1YhRSEhG9/MRcAUt2Biu+QEjwzL
            jXoftz4Jtzi06YzGedc6w38vEfDe+JBYU8qOLZ+OYs3V6b/+wrvtJxPbsvk1ZtbZ
            7goU/oMZ2k0sWqxaxFdvRNln2es9OKK5saaCNyBvDNeBHGCn9YKW8QUP1WW6V8Io
            hlT/fVASz2HD3rGhcUNF0v6/yu9dmwpHkfCGT56ynhfaiFVwa+FVwaALS9E/eqgP
            KUaDWoG8w4uD+3Ko4CVuVUrsdPjbxsU7rWhvqIGuWTetTW4a/kvma/Njxq/mHDun
            pcWoPwZ5PNFf71gJxcnfU9ocLE6+wKt/oTd/Bm6uy9JcAYDMOwinhJYrCmROgq/Q
            ws6Bqiyp0JkV3EvfzBz5Xoc5viuHnPwo0Cjgo12nPJpIjvx1S8X3cmito686RQRx
            wFkof+S+Z2SsqJv4nFIC5vzwBa5HFtsS7TuNeGA=
            =+OkQ
            -----END PGP MESSAGE-----
        fp: CD1AFE846A21A236CEF18FF56555786B3A496099
    encrypted_regex: ^(config)$
    version: 3.6.0
